### ISSUE TITLE
"Find path" stopped working because of open mapquest shutdown

### ISSUE THREAD

**Issue by ABelliqueux** [tboegi/GpsMaster#29]
Related to Issue #27 

When trying to use the find path tool, a red error message appears at the bottom of the window
with the caption `open.mapquestapi.com`.

It looks like mapquest shut down their open APIs in december 2022 according to this answer : https://stackoverflow.com/questions/74800230/did-mapquest-shutdown-their-elevation-api/74802749#74802749 and switched to a paid subscription model (https://developer.mapquest.com/plans).

Maybe there is an alternative service that could be used ? If this is too much work, maybe the feature could be removed or hidden by default ?

**Comment by tboegi** [comment]
Unless somebody comes with a better solution:
The "Find path" button is removed.
https://github.com/tboegi/GpsMaster/releases/tag/v0.64.03
