### ISSUE TITLE
Attempting to add points to "Waypoints" causes partial freeze.

### ISSUE THREAD

**Issue by john-h-kastner** [tboegi/GpsMaster#6]
If "Waypoints" is selected in the sidebar, and I attempt to add a route point, the map interface and explorer panel will freeze. 

# Steps to Reproduce

1. Create a new GPX file.
2. Add to this using the "Find path" tool.
3. Expand the entry in the explorer panel for the file you created.
3. There should be a "Waypoints" child node for the GPX file that was just created. Sometime this isn't the case, and I haven't figured out a pattern here. You may have to repeat these first three steps a couple times or try some other operations.
4. Once in a state where "Waypoints" is created, select it in the explorer panel
5. Using "Add Route Points", attempt to add a point.
6. You should now be unable to manipulate the map interface. 

# Workaround

Once in this state, the session can be recovered by clicking "Undo".

**Comment by rfuegen** [comment]
thanks for the bug report, I'll look into it.

**Comment by rfuegen** [comment]
I can reproduce the error, working on a fix. sorry for the long delay.

**Comment by rfuegen** [comment]
should be fixed, please check. 
the main problem here is that the GUI is quite inconsistent regarding the "add point" function (and possibly others, too).
- a "route point" is a point on a route
- a "waypoint" is an arbitray point on the map, basically the same as a POI
- "add route point" in the main toolbar also allowed to add waypoints, causing a crash when trying to paint them
- "add waypoints" is located in the (left-handed) toolbar, unfortunately with the same icon as "add route point"
- using the magic wand automatically creates a "waypoint" group, holding the locations where the user clicked on the map (route start- and endpoints)
- when adding route points manually immediately after creating the file, no waypoint group is added
- "add route point" button should be disabled when a waypoint group (or track) is selected (bug)
- after some actions, the GPX tree isn't always refreshed (bug)

hth.
