### ISSUE TITLE
What is the license of this?

### ISSUE THREAD

**Issue by KOLANICH** [tboegi/GpsMaster#8]

**Comment by Rakambda** [comment]
From https://wiki.openstreetmap.org/wiki/GpsMaster
> GpsMaster is a free (GNU GPL v2) and open source desktop application used to create

Could add a LICENSE file on the repository for it to be more visible maybe?

**Comment by KOLANICH** [comment]
>Could add a LICENSE file on the repository for it to be more visible maybe?

Yes, do it please. Maybe not `LICENSE`, but [`LICENSE.md`](https://www.gnu.org/licenses/old-licenses/gpl-2.0.md)

**Comment by tboegi** [comment]
@KOLANICH @RakSrinaNa all contributions are welcome.
Does anybody feel to contribute with a Pull-Request ?

**Comment by Rakambda** [comment]
GitHub can already generate a template for you. You just have to review it/adapt it as needed like you'd do with a PR:

https://github.com/tboegi/GpsMaster/new/master
![image](https://user-images.githubusercontent.com/1688389/108632582-0ab93080-7470-11eb-81f2-066f442838b5.png)
![image](https://user-images.githubusercontent.com/1688389/108632596-1f95c400-7470-11eb-908b-bb8e9029310e.png)

(Example is GNU v3 not GNU v2, didn't pay attention)
